import { Injectable, UnauthorizedException } from '@nestjs/common';
import { UsersService } from '../users/users.service.js';
import { JwtService } from '@nestjs/jwt';
import { UserDto } from '../../controllers/users/user.dto.js';

@Injectable()
export class AuthService {
  constructor(
    private usersService: UsersService,
    private jwtService: JwtService
) {}

  async signIn(
    username: string,
    pass: string,
  ): Promise<{ access_token: string }> {
    const user = await this.usersService.getUserByUsername(username);
    if (user?.password !== pass) {
      throw new UnauthorizedException();
    }
    const payload = { sub: user.id, username: user.username };
    return {
      // 💡 Here the JWT secret key that's used for signing the payload 
      // is the key that was passed in the JwtModule
      access_token: await this.jwtService.signAsync(payload),
    };
  }

  async register(userDto: UserDto): Promise<void> {
    const existingUser = await this.usersService.getUserByUsername(userDto.username);
    if (existingUser) {
      throw new UnauthorizedException('Username already exists');
    }
    await this.usersService.createUser({
      id: 0, // This will be auto-generated by the database
      name: userDto.name,
      email: userDto.email,
      username: userDto.username,
      password: userDto.password,
      role: 'user', // Default role for new users
    });
  }
}
